
// Commands
pub const CMD_RECALL_SCENE_GROUP: u32 = 11;
pub const CMD_RECALL_SCENE_DEVICE: u32 = 12;
pub const CMD_DIRECT_LEVEL_GROUP: u32 = 13;
pub const CMD_DIRECT_LEVEL_DEVICE: u32 = 14;
pub const CMD_DIRECT_PRPORTION_GROUP: u32 = 15;
pub const CMD_DIRECT_PRPORTION_DEVICE: u32 = 16;
pub const CMD_DIRECT_MODIFY_PROPORTION_GROUP: u32 = 17;
pub const CMD_DIRECT_MODIFY_PROPORTION_DEVICE: u32 = 18;
pub const CMD_EMERGENCY_FUNCTION_TEST_GROUP: u32 = 19;
pub const CMD_EMERGENCY_FUNCTION_TEST_DEVICE: u32 = 20;
pub const CMD_EMERGENCY_DURATION_TEST_GROUP: u32 = 21;
pub const CMD_EMERGENCY_DURATION_TEST_DEVICE: u32 = 22;
pub const CMD_STOP_EMERGENCY_TESTS_GROUP: u32 = 23;
pub const CMD_STOP_EMERGENCY_TESTS_DEVICE: u32 = 24;

pub const CMD_QUERY_LAMP_RUNNING_HOURS: u32 = 70;
pub const CMD_QUERY_BALLAST_RUNNING_HOURS: u32 = 71;
pub const CMD_QUERY_MAXIMUM_VOLTAGE: u32 = 72;
pub const CMD_QUERY_MINIMUM_VOLTAGE: u32 = 73;
pub const CMD_QUERY_MAXIMUM_TEMPERATURE: u32 = 74;
pub const CMD_QUERY_MINIMUM_TEMPERATURE: u32 = 75;

pub const CMD_QUERY_CLUSTERS: u32 = 101;
pub const CMD_QUERY_ROUTERS: u32 = 102;
pub const CMD_QUERY_LSIB: u32 = 103;
pub const CMD_QUERY_DEVICE_TYPE: u32 = 104;
pub const CMD_QUERY_DESCRIPTION_GROUP: u32 = 105;
pub const CMD_QUERY_DESCRIPTION_DEVICE: u32 = 106;
pub const CMD_QUERY_DEVICE_STATE: u32 = 110;
pub const CMD_QUERY_DEVICE_DISABLED: u32 = 111;
pub const CMD_QUERY_LAMP_FAILURE: u32 = 112;
pub const CMD_QUERY_DEVICE_FAULTY: u32 = 113;
pub const CMD_QUERY_DEVICE_MISSING: u32 = 114;
pub const CMD_QUERY_EMERGENCY_BATTERY_FAILURE: u32 = 129;
pub const CMD_QUERY_MEASUREMENT: u32 = 150;
pub const CMD_QUERY_INPUTS: u32 = 151;
pub const CMD_QUERY_LOAD_LEVEL: u32 = 152;
pub const CMD_QUERY_POWER_CONSUMPTION: u32 = 160;
pub const CMD_QUERY_GROUP_POWER_CONSUMPTION: u32 = 161;
pub const CMD_QUERY_EMERGENCY_FUNCTION_TEST_TIME: u32 = 170;
pub const CMD_QUERY_EMERGENCY_FUNCTION_TEST_STATE: u32 = 171;
pub const CMD_QUERY_EMERGENCY_DURATION_TEST_TIME: u32 = 172;
pub const CMD_QUERY_EMERGENCY_DURATION_TEST_STATE: u32 = 173;
pub const CMD_QUERY_EMERGENCY_BATTERY_CHARGE: u32 = 174;
pub const CMD_QUERY_EMERGENCY_BATTERY_TIME: u32 = 175;
pub const CMD_QUERY_EMERGENCY_TOTAL_LAMP_TIME: u32 = 176;
pub const CMD_QUERY_TIME: u32 = 185;
pub const CMD_QUERY_LONGITUDE: u32 = 186;
pub const CMD_QUERY_LATITUDE: u32 = 187;
pub const CMD_QUERY_TIMEZONE: u32 = 188;
pub const CMD_QUERY_DAYLIGHT_SAVING_TIME: u32 = 189;
pub const CMD_QUERY_SOFTWARE_VERSION: u32 = 190;
pub const CMD_QUERY_HELVARNET_VERSION: u32 = 191;

pub const CMD_STORE_SCENE_GROUP: u32 = 201;
pub const CMD_STORE_SCENE_DEVICE: u32 = 202;
pub const CMD_STORE_AS_SCENE_GROUP: u32 = 203;
pub const CMD_STORE_AS_SCENE_DEVICE: u32 = 204;
pub const CMD_RESET_EMERGENCE_TIME_GROUP: u32 = 205;
pub const CMD_RESET_EMERGENCE_TIME_DEVICE: u32 = 206;
pub const CMD_RESET_TIME_AND_LOCATION: u32 = 240;
pub const CMD_RESET_TIME: u32 = 241;
pub const CMD_SET_LONGITUDE: u32 = 242;
pub const CMD_SET_LATITUDE: u32 = 243;
pub const CMD_SET_TIMEZONE: u32 = 244;
pub const CMD_SET_DAYLIGHT_SAVING_TIME: u32 = 245;






